import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bell, Bolt, CalendarDays, ChevronDown, CircleHelp, Clock3, Command, FileText, LayoutDashboard, Menu, MoreHorizontal, Plus, Send, Settings, Sparkles, Users, X } from 'lucide-react';
import './styles.css';

const members = [
  { name: 'Priya Shah', role: 'QA engineer', initials: 'PS', color: 'peach', time: '10:18 AM', mood: 'Focused', yesterday: 'Completed checkout API regression suite.', today: 'Automating refund-flow test scenarios.', blocker: 'Needs staging credentials.' },
  { name: 'Arjun Mehta', role: 'Frontend engineer', initials: 'AM', color: 'lilac', time: '10:26 AM', mood: 'In flow', yesterday: 'Fixed the intermittent login error.', today: 'Building the notification preferences flow.', blocker: '' },
  { name: 'Sarah Williams', role: 'Product designer', initials: 'SW', color: 'blue', time: '12:04 PM', mood: 'Good', yesterday: 'Shared the onboarding concept with the client.', today: 'Refining empty states for the mobile app.', blocker: 'Waiting on client feedback.' },
  { name: 'Dev Rao', role: 'Backend engineer', initials: 'DR', color: 'lime', time: '12:15 PM', mood: 'Focused', yesterday: 'Optimised order status webhooks.', today: 'Adding audit logs to admin actions.', blocker: '' },
];
const pending = [{ name: 'Rahul Verma', initials: 'RV', color: 'orange' }, { name: 'Neha Kapoor', initials: 'NK', color: 'pink' }, { name: 'Vikram Nair', initials: 'VN', color: 'aqua' }];
const nav = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Today standup', icon: Bolt }, { label: 'Team', icon: Users }, { label: 'History', icon: CalendarDays }, { label: 'Insights', icon: Sparkles }];

function Avatar({ member, faded = false }) { return <div title={member.name} className={`avatar avatar-${member.color} ${faded ? 'faded' : ''}`}>{member.initials}</div>; }

function App() {
  const [active, setActive] = useState('Overview'); const [sidebar, setSidebar] = useState(false); const [notice, setNotice] = useState(''); const [showAll, setShowAll] = useState(false); const [setupOpen, setSetupOpen] = useState(false);
  const notify = (message) => { setNotice(message); window.setTimeout(() => setNotice(''), 2400); };
  return <div className="app-shell"><aside className={`sidebar ${sidebar ? 'is-open' : ''}`}><div className="brand"><span className="brand-star">*</span><span>pulse</span><button className="close" onClick={() => setSidebar(false)}><X size={18}/></button></div><div className="workspace-select"><span className="workspace-dot"/> Atlas Studio <ChevronDown size={15}/></div><nav>{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setSidebar(false); }} className={active === label ? 'active' : ''}><Icon size={18}/>{label}</button>)}</nav><div className="nav-bottom"><button><Settings size={18}/>Settings</button><button><CircleHelp size={18}/>Help centre</button></div><div className="user-card"><div className="avatar avatar-aqua">AK</div><div><strong>Ankit Kumar</strong><span>Admin</span></div><MoreHorizontal size={17}/></div></aside>{sidebar && <div className="scrim" onClick={() => setSidebar(false)}/>}<main><header className="topbar"><button className="menu-btn" onClick={() => setSidebar(true)}><Menu size={20}/></button><div className="crumb"><span>{active}</span><span className="slash">/</span><b>Monday, Jul 27</b></div><div className="top-actions"><button className="command"><Command size={14}/> K <span>Search</span></button><button className="icon-button"><Bell size={18}/><i/></button><div className="avatar avatar-aqua small">AK</div></div></header><section className="content"><div className="heading-row"><div><p className="eyebrow">YOUR DAILY PULSE <span>LIVE</span></p><h1>{active === 'Overview' ? <>Good morning, Ankit <span>*</span></> : active}</h1><p className="subheading">{active === 'Overview' ? 'Your team is moving. Here is what needs your attention.' : 'Keep your distributed team in sync, without another meeting.'}</p></div><button className="new-button" onClick={() => setSetupOpen(true)}><Plus size={18}/> New standup</button></div>{active === 'Overview' && <Overview notify={notify} showAll={showAll} setShowAll={setShowAll}/>} {active === 'Today standup' && <StandupPage notify={notify}/>} {active === 'Team' && <TeamPage notify={notify}/>} {['History', 'Insights'].includes(active) && <Placeholder page={active} notify={notify}/>}</section></main>{setupOpen && <SetupModal close={() => setSetupOpen(false)} notify={notify}/>} {notice && <div className="toast"><Sparkles size={17}/>{notice}</div>}</div>;
}

function Overview({ notify, showAll, setShowAll }) { const [live, setLive] = useState(null); useEffect(() => { fetch('http://localhost:3001/api/dashboard').then(r => r.ok ? r.json() : null).then(setLive).catch(() => setLive(null)); }, []); const liveMembers = live ? live.members.map((member, index) => { const answer = live.responses.find(item => item.userId === member.id); return { ...member, initials: member.name.split(' ').map(x => x[0]).join('').slice(0, 2), color: ['peach','lilac','blue','lime'][index % 4], role: 'Team member', time: answer?.status === 'completed' ? 'Submitted' : 'Pending', mood: answer?.status || 'pending', yesterday: answer?.yesterday || 'No update yet.', today: answer?.today || 'No update yet.', blocker: answer?.blockers || '' }; }) : members; const visible = showAll ? liveMembers : liveMembers.slice(0, 3); const completed = live?.responses.filter(item => item.status === 'completed').length || 0; return <><section className="pulse-card"><div className="pulse-copy"><div className="card-label"><span className="tiny-live"/> TODAY'S STANDUP</div><h2>{live ? `${completed} of ${liveMembers.length} checked in` : 'Loading standup...'}</h2><p>{live ? <><b>{live.standup.name}</b> - digest at <b>{live.standup.digestTime}</b></> : 'Fetching your Neon updates.'}</p><div className="progress"><span style={{ width: `${liveMembers.length ? Math.round(completed / liveMembers.length * 100) : 0}%` }}/></div></div><div className="pulse-actions"><span className="count-pill"><Clock3 size={14}/> Live Neon data</span><button className="dark-button" onClick={() => notify('Slack reminders come next.')}><Send size={16}/> Send a nudge</button></div></section><section className="updates-section"><div className="section-title"><div><p className="eyebrow">LIVE FROM YOUR TEAM</p><h2>Today updates <span className="update-count">{liveMembers.length}</span></h2></div></div><div className="update-list">{visible.map(m => <UpdateCard member={m} key={m.id || m.name} notify={notify}/>)}</div>{!showAll && liveMembers.length > 3 && <button className="load-button" onClick={() => setShowAll(true)}>Load more updates</button>}</section></>; }
function UpdateCard({ member, notify }) { return <article className="update-card"><div className="update-top"><Avatar member={member}/><div><h3>{member.name} <span className="role">{member.role}</span></h3><p><span className="status-dot"/> Checked in at {member.time}</p></div><span className="mood-pill">{member.mood}</span><button className="more"><MoreHorizontal size={19}/></button></div><div className="update-body"><div><label>YESTERDAY</label><p>{member.yesterday}</p></div><div><label>TODAY</label><p>{member.today}</p></div>{member.blocker && <div className="update-blocker"><label>BLOCKER</label><p>Blocked: {member.blocker}</p></div>}</div><div className="update-footer"><button onClick={() => notify(`Reaction sent to ${member.name}.`)}>Appreciate</button><button onClick={() => notify(`Opening Slack DM with ${member.name}.`)}>Follow up</button></div></article>; }
function StandupPage({ notify }) { return <><section className="standup-hero"><div><p className="card-label"><span className="tiny-live"/> RUNNING NOW</p><h2>Engineering daily</h2><p>Prompts went out at 10:00 AM in each member local time.</p></div><div className="standup-hero-actions"><button className="dark-button" onClick={() => notify('Daily digest posted to #daily-standup.')}>Post digest now</button><button className="outline-button" onClick={() => notify('Reminder sent to 3 pending members.')}>Remind 3 people</button></div></section><section className="kanban"><div className="kanban-col"><header><span className="kanban-dot done"/> Checked in <b>7</b></header>{members.map(m => <div className="member-chip" key={m.name}><Avatar member={m}/><div><strong>{m.name}</strong><span>{m.mood} - {m.time}</span></div><span className="check">OK</span></div>)}</div><div className="kanban-col"><header><span className="kanban-dot working"/> In progress <b>0</b></header><div className="empty-state">No replies in progress.<br/>Partial answers appear here.</div></div><div className="kanban-col"><header><span className="kanban-dot waiting"/> Waiting <b>3</b></header>{pending.map(m => <div className="member-chip" key={m.name}><Avatar member={m}/><div><strong>{m.name}</strong><span>Prompted at 10:00 AM</span></div><button onClick={() => notify(`Reminder sent to ${m.name}.`)}>Nudge</button></div>)}</div></section><section className="digest-preview"><div><p className="eyebrow">SLACK PREVIEW</p><h2>Today digest</h2></div><div className="slack-message"><b>Engineering daily standup</b><span>Monday, July 27 - 7/10 responses</span><hr/><strong>Blockers</strong><p>Priya - Needs staging credentials<br/>Sarah - Waiting on client feedback</p><strong>No update yet</strong><p>Rahul, Neha, Vikram</p></div></section></>; }
function TeamPage({ notify }) {
  const [teams, setTeams] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadTeams = async () => {
      try {
        const response = await fetch('http://localhost:3001/api/teams');
        if (!response.ok) {
          throw new Error('Unable to load teams');
        }
        const data = await response.json();
        setTeams(data);
      } catch (error) {
        console.error('Failed to load teams from backend', error);
        setTeams([]);
      } finally {
        setLoading(false);
      }
    };

    loadTeams();
  }, []);

  return <section className="team-panel"><div className="section-title"><div><p className="eyebrow">{loading ? 'LOADING TEAM DATA' : `${teams.length} TEAM${teams.length === 1 ? '' : 'S'}`}</p><h2>Your standup team</h2></div><button className="outline-button" onClick={() => notify('Slack member picker will open here.')}>+ Add people</button></div>{loading ? <div className="empty-state">Loading teams from the backend…</div> : teams.length === 0 ? <div className="empty-state">No team rows were returned from Neon yet.</div> : teams.map((team) => <div className="team-row" key={team.id}><Avatar member={{ name: team.name, initials: team.name.slice(0, 2).toUpperCase(), color: 'aqua' }}/><div><strong>{team.name}</strong><span>{team.timezone || 'Timezone pending'} • synced from Neon</span></div><span className="active-tag">Active</span><button className="more"><MoreHorizontal size={19}/></button></div>)}</section>; }
function SetupModal({ close, notify }) { const save = () => { notify('Standup configuration saved.'); close(); }; return <div className="modal-wrap"><div className="modal-scrim" onClick={close}/><div className="setup-modal"><button className="modal-close" onClick={close}><X size={18}/></button><p className="eyebrow">CREATE STANDUP</p><h2>Set your team rhythm.</h2><p className="modal-sub">A small setup now. No more calendar meetings later.</p><label className="form-label">STANDUP NAME<input defaultValue="Engineering daily"/></label><div className="form-grid"><label className="form-label">PROMPT TIME<select defaultValue="10:00 AM"><option>10:00 AM</option><option>9:30 AM</option><option>11:00 AM</option></select></label><label className="form-label">DIGEST TIME<select defaultValue="5:30 PM"><option>5:30 PM</option><option>5:00 PM</option><option>6:00 PM</option></select></label></div><label className="form-label">POST TO<select defaultValue="#daily-standup"><option>#daily-standup</option><option>#engineering</option><option>#team-updates</option></select></label><div className="questions"><p>DAILY QUESTIONS <span>3 fixed for MVP</span></p><ol><li>What did you do yesterday?</li><li>What are you doing today?</li><li>Any blockers?</li></ol></div><button className="dark-button full" onClick={save}>Save standup</button></div></div>; }
function Placeholder({ page, notify }) { return <div className="placeholder"><div className="placeholder-icon">*</div><h2>{page} is ready for the next layer.</h2><p>The core standup experience is complete. This page will be expanded after Slack and Neon are connected.</p><button className="dark-button" onClick={() => notify(`${page} is planned for the next iteration.`)}>Explore {page}</button></div>; }
createRoot(document.getElementById('root')).render(<App/>);
