import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bell, Bolt, CalendarDays, ChevronDown, CircleHelp, LayoutDashboard, Menu, MoreHorizontal, Plus, Settings, Users, X } from 'lucide-react';
import './styles.css';

const nav = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Today standup', icon: Bolt }, { label: 'Team', icon: Users }, { label: 'History', icon: CalendarDays }];
const colors = ['peach', 'lilac', 'blue', 'lime'];
const api = 'http://localhost:3001/api/dashboard';
const initials = (name = 'Member') => name.split(' ').map((word) => word[0]).join('').slice(0, 2).toUpperCase();
function Avatar({ member, index = 0 }) { return <div className={`avatar avatar-${colors[index % colors.length]}`}>{initials(member.name)}</div>; }

function App() {
  const [active, setActive] = useState('Overview'); const [sidebar, setSidebar] = useState(false); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [setup, setSetup] = useState(false);
  const load = () => { setLoading(true); fetch(api).then((r) => r.ok ? r.json() : null).then(setData).finally(() => setLoading(false)); };
  useEffect(load, []);
  const today = new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'short', day: 'numeric' }).format(new Date());
  return <div className="app-shell"><aside className={`sidebar ${sidebar ? 'is-open' : ''}`}><div className="brand"><span className="brand-star">*</span>pulse<button className="close" onClick={() => setSidebar(false)}><X size={18}/></button></div><div className="workspace-select"><span className="workspace-dot"/>{data?.standup?.teamName || 'Your workspace'}<ChevronDown size={15}/></div><nav>{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setSidebar(false); }} className={active === label ? 'active' : ''}><Icon size={18}/>{label}</button>)}</nav><div className="nav-bottom"><button><Settings size={18}/>Settings</button><button><CircleHelp size={18}/>Help centre</button></div></aside>{sidebar && <div className="scrim" onClick={() => setSidebar(false)}/>}<main><header className="topbar"><button className="menu-btn" onClick={() => setSidebar(true)}><Menu size={20}/></button><div className="crumb"><span>{active}</span><span className="slash">/</span><b>{today}</b></div><div className="top-actions"><button className="icon-button"><Bell size={18}/><i/></button><div className="avatar avatar-aqua small">AK</div></div></header><section className="content">{active === 'Overview' && <Overview data={data} loading={loading}/>} {active === 'Today standup' && <Today data={data} loading={loading} openSetup={() => setSetup(true)}/>} {active === 'Team' && <Team data={data} loading={loading}/>} {active === 'History' && <Empty title="Standup history" text="Completed daily digests will appear here."/>}</section></main>{setup && <Setup close={() => setSetup(false)}/>}</div>;
}

function Overview({ data, loading }) { const total = data?.members?.length || 0; const done = data?.responses?.filter((item) => item.status === 'completed').length || 0; return <><div className="heading-row"><div><p className="eyebrow">YOUR DAILY PULSE <span>LIVE</span></p><h1>Good morning, Ankit <span>*</span></h1><p className="subheading">Your team updates, without the meeting.</p></div></div><section className="pulse-card"><div className="pulse-copy"><div className="card-label"><span className="tiny-live"/> TODAY'S STANDUP</div><h2>{loading ? 'Loading updates...' : `${done} of ${total} checked in`}</h2><p>{data ? <><b>{data.standup.name}</b> - digest at <b>{data.standup.digestTime}</b></> : 'Connect Slack and send “standup” to your bot.'}</p><div className="progress"><span style={{ width: `${total ? Math.round(done / total * 100) : 0}%` }}/></div></div></section><section className="updates-section"><div className="section-title"><div><p className="eyebrow">LIVE FROM YOUR TEAM</p><h2>Today updates <span className="update-count">{total}</span></h2></div></div>{!loading && !total && <Empty title="No Slack members yet" text="Members appear here after they message your Slack bot."/>}<div className="update-list">{data?.members?.map((member, index) => { const response = data.responses.find((item) => item.userId === member.id); return <article className="update-card" key={member.id}><div className="update-top"><Avatar member={member} index={index}/><div><h3>{member.name}</h3><p><span className="status-dot"/> {response?.status === 'completed' ? 'Checked in' : 'Waiting for update'}</p></div></div>{response?.status === 'completed' && <div className="update-body"><div><label>YESTERDAY</label><p>{response.yesterday}</p></div><div><label>TODAY</label><p>{response.today}</p></div>{response.blockers && <div className="update-blocker"><label>BLOCKER</label><p>{response.blockers}</p></div>}</div>}</article>; })}</div></section></>; }
function Today({ data, loading, openSetup }) { return <><div className="heading-row"><div><p className="eyebrow">DAILY RHYTHM</p><h1>Today standup</h1><p className="subheading">Start a standup in Slack, then answers arrive here.</p></div><button className="new-button" onClick={openSetup}><Plus size={18}/> New standup</button></div><section className="standup-hero"><div><p className="card-label"><span className="tiny-live"/> RUNNING NOW</p><h2>{data?.standup?.name || 'No active standup'}</h2><p>{loading ? 'Loading schedule...' : data ? `Prompt: ${data.standup.promptTime} · Digest: ${data.standup.digestTime}` : 'Create or connect a standup to begin.'}</p></div></section><section className="digest-preview"><div><p className="eyebrow">HOW TO RESPOND</p><h2>Slack bot flow</h2></div><div className="slack-message"><b>DM your Pulse app:</b><p>standup</p><strong>Then answer three questions.</strong><p>Your response saves automatically and appears on this page.</p></div></section></>; }
function Team({ data, loading }) { return <><div className="heading-row"><div><p className="eyebrow">SLACK MEMBERS</p><h1>Your team</h1><p className="subheading">Members join automatically after sending the bot a standup.</p></div></div><section className="team-panel">{loading && <div className="empty-state">Loading Slack members...</div>}{!loading && !data?.members?.length && <div className="empty-state">No members yet. Ask a teammate to DM the app: <b>standup</b>.</div>}{data?.members?.map((member, index) => <div className="team-row" key={member.id}><Avatar member={member} index={index}/><div><strong>{member.name}</strong><span>{member.timezone || 'Timezone pending'} · Slack member</span></div><span className="active-tag">Active</span><button className="more"><MoreHorizontal size={19}/></button></div>)}</section></>; }
function Setup({ close }) { return <div className="modal-wrap"><div className="modal-scrim" onClick={close}/><div className="setup-modal"><button className="modal-close" onClick={close}><X size={18}/></button><p className="eyebrow">NEW STANDUP</p><h2>Configure in Slack first.</h2><p className="modal-sub">The current MVP creates a default standup automatically when a Slack member sends “standup”. Custom schedules are the next enhancement.</p><button className="dark-button full" onClick={close}>Got it</button></div></div>; }
function Empty({ title, text }) { return <div className="placeholder"><div className="placeholder-icon">*</div><h2>{title}</h2><p>{text}</p></div>; }
createRoot(document.getElementById('root')).render(<App/>);
